services:
  # 1. ส่วน Database (MySQL)
  novis-db:
    image: mysql:8.0
    container_name: novis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'noviscraft_db'
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  # 2. ส่วนจัดการ Database (phpMyAdmin)
  novis-pma:
    image: phpmyadmin:latest
    container_name: novis-pma
    restart: always
    ports:
      - '8181:80'
    environment:
      PMA_HOST: novis-db
      MYSQL_ROOT_PASSWORD: '1234'

  # 3. ส่วน Web Server สำหรับหน้าเว็บเติมเงิน (PHP + Apache)
  novis-web:
    image: php:8.1-apache
    container_name: novis-web
    restart: always
    ports:
      - '80:80' # เข้าเว็บผ่าน localhost ได้เลย
    volumes:
      - ./web:/var/www/html # เก็บไฟล์เว็บไว้ในโฟลเดอร์ web
    depends_on:
      - novis-db